"""Task 20 -- validate the real canonical -> Bronze -> Silver contract against every canonical
JSONL file actually on disk (Task 17's legacy-parser output, generated by
scripts/parsing/run_task17_canonical.py, plus Task 19's Tier-1 output from
scripts/parsing/tier1/run_tier1.py). Read-only against data/parsed/canonical/; writes only to
data/analytics/lakehouse/ (gitignored, like every other data/analytics/ output).

Uses databricks/src/common/local_validation.py -- NOT a live SparkSession (pyspark is not
installed in this environment; see databricks/README.md). This is stated explicitly in every
output artifact, not hidden.

Usage: python scripts/lakehouse/validate_lakehouse.py
"""

from __future__ import annotations

import json
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from databricks.src.common.local_validation import bronze_dedupe, run_bronze_silver  # noqa: E402
from pipeline.canonical.domain_registry import DOMAIN_REGISTRY, assert_registry_matches_contracts  # noqa: E402

CANONICAL_ROOT = PROJECT_ROOT / "data" / "parsed" / "canonical"
ANALYTICS_ROOT = PROJECT_ROOT / "data" / "analytics" / "lakehouse"


def _read_jsonl(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def _discover() -> dict[str, dict[str, list[dict]]]:
    """domain -> {source_file_stem: records}. Every *.jsonl directly under
    data/parsed/canonical/<domain>/ is included (both task17_* and tier1_* outputs); files
    starting with "_" (e.g. _task17_quarantine.jsonl) are not canonical records."""
    found: dict[str, dict[str, list[dict]]] = defaultdict(dict)
    if not CANONICAL_ROOT.exists():
        return found
    for domain_dir in sorted(p for p in CANONICAL_ROOT.iterdir() if p.is_dir()):
        for jsonl_file in sorted(domain_dir.glob("*.jsonl")):
            if jsonl_file.name.startswith("_"):
                continue
            found[domain_dir.name][jsonl_file.stem] = _read_jsonl(jsonl_file)
    return found


def _geo_counts(records: list[dict]) -> dict[str, int]:
    counts = Counter()
    for r in records:
        status = r.get("resolution_status")
        counts[status if status else "no_status_field"] += 1
    return dict(sorted(counts.items()))


def _provenance_check(records: list[dict]) -> dict[str, int]:
    core = ("source_organization", "source_dataset", "parser_version", "normalization_version")
    present = {f: sum(1 for r in records if (r.get("provenance") or {}).get(f)) for f in core}
    return {"total": len(records), **present}


def _idempotency_check(records: list[dict]) -> dict[str, Any]:
    first = bronze_dedupe(records)
    second = bronze_dedupe(records)
    doubled = bronze_dedupe(records + records)
    return {
        "same_input_twice_identical": sorted(json.dumps(r, sort_keys=True) for r in first) ==
                                      sorted(json.dumps(r, sort_keys=True) for r in second),
        "duplicate_injection_no_row_multiplication": len(doubled) == len(first),
        "unique_count": len(first),
    }


def main():
    mismatches = assert_registry_matches_contracts()
    found = _discover()

    bronze_summary, silver_summary, quality_report = {}, {}, {}
    for domain in sorted(DOMAIN_REGISTRY):
        sources = found.get(domain, {})
        all_records = [r for recs in sources.values() for r in recs]
        per_source = {name: len(recs) for name, recs in sorted(sources.items())}

        if not all_records:
            bronze_summary[domain] = {"status": "no_canonical_data_found", "sources": per_source}
            silver_summary[domain] = {"status": "no_canonical_data_found"}
            quality_report[domain] = {"status": "no_canonical_data_found", "sources": per_source}
            continue

        result = run_bronze_silver(all_records, domain)
        idem = _idempotency_check(all_records)

        bronze_summary[domain] = {
            "sources": per_source, "input_records": result["input_records"],
            "bronze_unique_records": result["bronze_unique_records"],
            "duplicates_removed": result["duplicates_removed"], "bronze_contract": result["bronze"],
            "idempotency": idem,
        }
        silver_summary[domain] = {"silver_contract": result["silver"],
                                  "required_non_null_any": list(DOMAIN_REGISTRY[domain].required_non_null_any),
                                  "timestamp_fields_checked": list(DOMAIN_REGISTRY[domain].timestamp_fields)}
        quality_report[domain] = {
            "sources": per_source, "geography_applicable": DOMAIN_REGISTRY[domain].geography_applicable,
            "geography": _geo_counts(all_records) if DOMAIN_REGISTRY[domain].geography_applicable else "not_attempted_by_design",
            "provenance": _provenance_check(all_records),
        }

    report = {
        "generated_by": "scripts/lakehouse/validate_lakehouse.py",
        "spark_execution_status": "NOT EXECUTED -- pyspark is not installed in this environment; "
                                  "this report was produced by databricks/src/common/local_validation.py, "
                                  "a pure-Python stand-in that reuses the real Spark modules' dedup/timestamp "
                                  "configuration (see docs/architecture/CANONICAL_BRONZE_SILVER_STATUS.md)",
        "domain_registry_consistency": {"mismatches": mismatches, "status": "ok" if not mismatches else "MISMATCH"},
        "domains": quality_report,
    }

    ANALYTICS_ROOT.mkdir(parents=True, exist_ok=True)
    for name, payload in (("bronze_validation_summary.json", bronze_summary),
                          ("silver_validation_summary.json", silver_summary),
                          ("lakehouse_quality_report.json", report)):
        (ANALYTICS_ROOT / name).write_text(json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
                                           encoding="utf-8")
    return report


if __name__ == "__main__":
    print(json.dumps(main()["domain_registry_consistency"], indent=2))
