"""Operational Intelligence section (Task 40): the former 9_Agent.py page as a render() function. Logic unchanged."""



from datetime import date

import streamlit as st

from dashboard.api_client import RiskApiClient
from dashboard.utils.agent_helpers import BASELINE_LABEL, candidate_rows, ml_rows, provenance_rows, routing_text, status_banner, tool_trace_table
from dashboard.utils.intelligence_helpers import area_options, risk_metrics, score_caption, signal_summary
from dashboard.utils.rag_helpers import MODES, evidence_caption, relevance_notice




@st.cache_resource
def _client() -> RiskApiClient:
    return RiskApiClient()


@st.cache_data(ttl=300, show_spinner=False)
def _units(base_url: str):
    c = _client()
    rows = []
    for level in (1, 2):
        res = c.admin_units(level=level)
        if res.ok and res.data:
            rows += [{"id": u["id"], "name": u["name"], "level": u["level"], "province": u.get("province")} for u in res.data]
    return rows



def render() -> None:
    st.subheader("🤖 Operational Intelligence Agent")
    st.caption("A read-only, provenance-aware agent that orchestrates existing PORI capabilities (risk engine, documentary evidence, ML forecasts, geography). "
               "It cannot write, run SQL or invent facts. Decision support only - not an official warning.")

    base = _client().base_url
    options = area_options(_units(base))
    with st.form("agent"):
        question = st.text_input("Your question", placeholder="e.g. Why is Lahore currently classified LOW and is there any AQI forecast?")
        c1, c2, c3 = st.columns(3)
        area = c1.selectbox("Area", list(options))
        mode = c2.selectbox("Evidence retrieval", list(MODES), format_func=MODES.get)
        llm_routing = c3.checkbox("Allow LLM-assisted routing when a model is configured", value=True)
        use_date = st.checkbox("Look up the risk on a specific date (otherwise the latest available)")
        risk_date = st.date_input("Risk date", value=date.today()) if use_date else None
        submitted = st.form_submit_button("Ask the agent")

    if submitted:
        if len((question or "").strip()) < 2:
            st.warning("Please type a question (at least 2 characters).")
            st.stop()
        with st.spinner("Running the agent's read-only tools..."):
            res = _client().agent(question.strip(), mode=mode, admin_unit_id=options[area], date=risk_date.isoformat() if risk_date else None,
                                  routing="auto" if llm_routing else "deterministic")
        body = res.data if isinstance(res.data, dict) and "tool_trace" in res.data else None
        if body is None:
            st.error(f"Could not get a result: {res.message}")
            if res.error_kind == "connection":
                st.caption("The service is not reachable. Start the API with: docker compose up -d --build api "
                           "(or: uvicorn api.app.main:app --port 8000). Override the address with PORI_API_URL.")
            st.stop()

        status = body["status"]
        level, message = status_banner(status)
        getattr(st, level)(f"**{status}** - {message}")
        if body.get("status_reason"):
            st.caption(f"Reason: {body['status_reason']}" + (f" ({body['reason_code']})" if body.get("reason_code") else ""))
        m1, m2, m3, m4 = st.columns(4)
        m1.metric("Detected intent", body.get("intent") or "-")
        m2.metric("Agent status", status)
        m3.metric("Routing", routing_text(body.get("trace")))
        m4.metric("Tools run", str(len([t for t in body.get("tool_trace") or [] if t.get("status") != "INVALID_TOOL_CALL"])))

        # ---------------------------------------------------------------- final answer (only when a real model produced and the validator accepted it)
        st.subheader("Answer")
        if status == "ANSWERED" and body.get("answer"):
            st.markdown(body["answer"])
            mdl = body.get("model") or {}
            st.caption(f"Generated by {mdl.get('provider')} / {mdl.get('model')}. [risk_engine] = risk engine record, [ml_prediction] = ML/baseline forecast, "
                       "[chunk:...] = a retrieved document passage.")
        else:
            st.caption("No natural-language answer is available for this request. The structured results below are the agent's output.")

        pc = body.get("premise_check")
        if pc and not pc.get("matches"):
            st.warning(f"False premise: {pc['note']}")

        # ---------------------------------------------------------------- geography
        geo = body.get("geography")
        if geo and (geo.get("candidates") or geo.get("unit")):
            st.subheader("Geography")
            st.caption("Provenance: GEOGRAPHY (canonical admin units; exact / alias / normalised matches only, never fuzzy).")
            if geo.get("candidates"):
                st.dataframe(candidate_rows(geo["candidates"]), hide_index=True, use_container_width=True)
            elif geo.get("unit"):
                u = geo["unit"]
                st.write(f"{u.get('name')} (admin_unit_id {u.get('id')}, level {u.get('level')}, province {u.get('province')})")

        # ---------------------------------------------------------------- risk context
        st.subheader("Operational Risk Context")
        rcx = body.get("risk_context")
        if rcx is None:
            st.caption("The risk engine was not consulted for this question.")
        elif rcx["status"] == "AVAILABLE":
            rec = rcx["record"]
            st.caption("Provenance: RISK_ENGINE (computed). Documents below are not inputs to this classification.")
            for col, (label, value) in zip(st.columns(5), risk_metrics(rec).items()):
                col.metric(label, value)
            st.caption(f"{rec['admin_unit_name']} | risk date {rec['risk_date']} ({(rcx.get('lookup') or {}).get('basis')}) | basis {rec.get('risk_basis')} | "
                       f"engine {rec['calculation_version']} | thresholds {rec.get('threshold_status')}")
            st.caption(score_caption(rec))
            sig = signal_summary(rec.get("signals"))
            sig["value"] = sig["value"].astype(str)
            st.dataframe(sig, hide_index=True, use_container_width=True)
        else:
            st.info(f"NO_RISK_CONTEXT - {rcx.get('reason')}")

        # ---------------------------------------------------------------- ML forecast
        st.subheader("ML Forecast (not a current risk status)")
        ml = body.get("ml_prediction")
        comp_ml = (body.get("components") or {}).get("ml")
        if ml:
            st.caption("Provenance: " + " + ".join(ml.get("attributions") or ["ML_MODEL"]) + ". A forecast of an observed quantity at a future date; it does not change any risk classification.")
            if ml.get("baseline_label") or not ml.get("validated_against_baseline"):
                st.warning(f"**{BASELINE_LABEL}** - the machine-learning candidates did not beat a simple baseline on held-out data, so these values are that baseline's forecast.")
            st.dataframe(ml_rows(ml["predictions"]), hide_index=True, use_container_width=True)
            st.caption("No calibrated probability or confidence interval is available.")
        elif comp_ml and comp_ml.get("status") == "INSUFFICIENT_DATA":
            st.info(f"INSUFFICIENT_DATA - {comp_ml.get('reason')}")
        else:
            st.caption("The ML prediction layer was not consulted for this question.")

        # ---------------------------------------------------------------- documentary evidence
        st.subheader("Documentary Evidence")
        r = body.get("retrieval") or {}
        if r:
            st.caption(f"Provenance: RAG_DOCUMENT | retrieval: {r.get('mode')} ({r.get('method')}) | filters applied {r.get('filters_applied')}"
                       + (f" | relaxed: {', '.join(r['filters_relaxed'])}" if r.get("filters_relaxed") else ""))
        cited = {c["chunk_id"] for c in body.get("citations") or [] if c.get("kind") == "documentary"}
        notice = relevance_notice(r)
        if notice:
            getattr(st, notice[0])(notice[1])
        if not body.get("documentary_evidence"):
            st.caption("No documentary evidence was retrieved" + ("." if r else " (the documents were not consulted for this question)."))
        for e in body.get("documentary_evidence") or []:
            with st.expander(f"{'✅ ' if e['chunk_id'] in cited else ''}{e.get('title') or '(untitled)'} - {e['chunk_id']}"):
                st.caption(evidence_caption(e))
                st.text(e.get("snippet") or "")

        # ---------------------------------------------------------------- provenance + trace
        st.subheader("Provenance")
        st.dataframe(provenance_rows(body), hide_index=True, use_container_width=True)
        g = body.get("groundedness") or {}
        for w in g.get("warnings") or []:
            st.warning(f"Number {w.get('number')} not found in the cited source: {w.get('sentence')}")
        if status == "INVALID_ANSWER":
            with st.expander("Why the answer was withheld"):
                st.json(g.get("problems") or [])
        st.subheader("Tool Trace")
        st.caption("Every tool the agent called (or a model proposed), with its validated arguments, status and provenance. Rejected calls were never executed.")
        st.dataframe(tool_trace_table(body.get("tool_trace")), hide_index=True, use_container_width=True)
        with st.expander("Full audit trace (JSON)"):
            st.json(body.get("trace") or {})
        st.caption(body.get("disclaimer") or "")
