"""
tests/parsers/test_pdma_golden.py

Phase 1 / Task 8 (ADR-0001) -- golden-file regression tests for the
three PDMA per-type parser functions, run against real PDMA PDFs
already tracked under data/raw/pdma/:

  - scripts/parsing/parse_pdma_daily.py::parse_pdf()
  - scripts/parsing/parse_rainfall.py::parse_rainfall_report()
  - scripts/parsing/parse_gauge.py::parse_pdf()

These three functions are tested directly rather than through the
scripts/parsing/parse_pdma.py orchestrator, because that orchestrator
uses a bare `from parse_pdma_daily import parse_pdf as parse_daily`
style import that (like parse_ndma.py's `common` import) only resolves
when scripts/parsing is on sys.path via the script's own directory
being auto-inserted -- workable for the orchestrator's own standalone
run, but not something Task 8 needs to route through when the
individual parser functions are cleanly, properly package-qualified
importable on their own (`scripts.parsing.parse_pdma_daily`,
`scripts.parsing.parse_rainfall`, `scripts.parsing.parse_gauge`).
Because of this, the parsed records asserted on here do NOT include a
"validation" key -- that key is only added by parse_pdma.py's
orchestration layer (schema/completeness/score), not by the parser
functions themselves.

Coverage note (reported, not silently worked around): no earthquake
PDMA fixture exists -- data/raw/pdma/reports/earthquake_reports/ has
zero PDFs in either 2025 or 2026, and no parser function for that
report type exists anywhere in the repo. Earthquake is out of scope
for this task.

Expected-output JSON under tests/fixtures/expected/pdma/<domain>/ was
generated by actually running the current parser against each chosen
PDF and hand-reviewing the result.

All three parser functions are pure (no file writes, no DB writes, no
quarantine calls) -- confirmed by reading their source this session --
so no monkeypatching/isolation is required to run them safely.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from scripts.parsing.parse_pdma_daily import parse_pdf as parse_daily
from scripts.parsing.parse_rainfall import parse_rainfall_report as parse_rainfall
from scripts.parsing.parse_gauge import parse_pdf as parse_gauge

PROJECT_ROOT = Path(__file__).resolve().parents[2]
PDMA_RAW_ROOT = PROJECT_ROOT / "data" / "raw" / "pdma" / "reports"
EXPECTED_ROOT = Path(__file__).resolve().parent.parent / "fixtures" / "expected" / "pdma"

# Fields whose value legitimately differs on every run (wall-clock
# timestamps) and must be excluded from exact-match comparison.
VOLATILE_FIELDS = {"created_at"}

DAILY_FIXTURES = [
    ("2025", "PDMA%20Daily%20Situation%20Report%2002%20June%202025_2030%20HRS.pdf"),
    ("2025", "PDMA%20Daily%20Situation%20Report%2001%20November%202025_0900%20HRS.pdf"),
    ("2026", "01%20June%202026_1000%20HRS.pdf"),
    ("2026", "01%20September%20%202026_1000HRS.pdf"),
    ("2026", "02%20July%202026_1000%20HRS.pdf"),
]

RAINFALL_FIXTURES = [
    ("2025", "Total%20Rainfall%20%28mm%29%20Last%2024%20hours%20%2801.08.2025%29.pdf"),
    ("2025", "Total%20Rainfall%20%28mm%29%20Last%2024%20hours%20%2803.03.2025%29.pdf"),
    ("2025", "Total%20Rainfall%20%28mm%29%20Last%2024%20hours%20%2802.05.2025%29.pdf"),
    ("2026", "Last%2024%20hours_02.07.2026.pdf"),
    ("2026", "Rainfall%20%28mm%29%20Last%2024%20hours%20%2805.06.2026%29.pdf"),
]

GAUGE_FIXTURES = [
    ("2025", "PDMA_GAUGES_AND_RIVERS_SITUATION_REPORT_01-07-2025_1200_HRS.pdf"),
    ("2025", "PDMA_GAUGES_AND_RIVERS_SITUATION_REPORT_01-09-2025_1300_HRS.pdf"),
    ("2026", "01.07.2026_0000Hrs.pdf"),
    ("2026", "01.07.2026_1200Hrs.pdf"),
    ("2026", "01.08.2026_0000Hrs.pdf"),
]


def _strip_volatile(record: dict) -> dict:
    return {k: v for k, v in record.items() if k not in VOLATILE_FIELDS}


def _assert_matches_golden(domain, stem, actual):
    expected_path = EXPECTED_ROOT / domain / f"{stem}.json"
    assert expected_path.exists(), f"missing golden fixture: {expected_path}"
    with open(expected_path, encoding="utf-8") as f:
        expected = json.load(f)
    assert _strip_volatile(actual) == _strip_volatile(expected)


# ==========================================================
# DAILY
# ==========================================================

@pytest.mark.parametrize("year,filename", DAILY_FIXTURES)
def test_pdma_daily_golden(year, filename):
    pdf_path = PDMA_RAW_ROOT / "daily_reports" / year / "pdfs" / filename
    assert pdf_path.exists(), f"fixture PDF missing from data/raw: {pdf_path}"

    result = parse_daily(pdf_path)

    assert result["report_type"] == "daily"
    assert result["report_year"] == year
    assert result["source_file"] == filename

    _assert_matches_golden("daily", Path(filename).stem, result)


# ==========================================================
# RAINFALL
# ==========================================================

@pytest.mark.parametrize("year,filename", RAINFALL_FIXTURES)
def test_pdma_rainfall_golden(year, filename):
    pdf_path = PDMA_RAW_ROOT / "rainfall_reports" / year / "pdfs" / filename
    assert pdf_path.exists(), f"fixture PDF missing from data/raw: {pdf_path}"

    result = parse_rainfall(pdf_path)

    assert result["report_type"] == "rainfall"
    assert result["report_year"] == year
    assert result["source_file"] == filename
    assert result["station_count"] == len(result["stations"])

    _assert_matches_golden("rainfall", Path(filename).stem, result)


# ==========================================================
# GAUGE
# ==========================================================

@pytest.mark.parametrize("year,filename", GAUGE_FIXTURES)
def test_pdma_gauge_golden(year, filename):
    pdf_path = PDMA_RAW_ROOT / "gauge_reports" / year / "pdfs" / filename
    assert pdf_path.exists(), f"fixture PDF missing from data/raw: {pdf_path}"

    result = parse_gauge(pdf_path)

    assert result["report_type"] == "gauge"
    assert result["source_file"] == filename
    assert result["gauge_count"] == len(result["gauges"])

    _assert_matches_golden("gauge", Path(filename).stem, result)


# ==========================================================
# COVERAGE GAP -- reported, not silently worked around
# ==========================================================

def test_pdma_earthquake_reports_have_no_parser_and_no_fixtures():
    """
    Documents a real, pre-existing gap rather than hiding it: the
    earthquake_reports raw directories exist but are empty, and no
    parser function for this report type exists anywhere in the repo.
    This test fails loudly (rather than being silently absent) if a
    parser or fixtures are ever added without updating this note.
    """
    for year in ("2025", "2026"):
        pdfs_dir = PDMA_RAW_ROOT / "earthquake_reports" / year / "pdfs"
        if pdfs_dir.exists():
            assert list(pdfs_dir.glob("*.pdf")) == [], (
                f"earthquake PDFs now exist under {pdfs_dir} but Task 8 was "
                f"written when there were none and no parser existed -- "
                f"this suite needs updating, not silently skipping."
            )

    import importlib.util

    assert importlib.util.find_spec("scripts.parsing.parse_earthquake") is None, (
        "an earthquake parser module now exists -- Task 8's fixtures/tests "
        "need to be extended to cover it."
    )
